name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 16.171.3.251
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd devops-sec-ca
          git pull origin main
          npm install
          pm2 restart devops-app
